version: "3"
services: 
  master-db:
    build: 
      context: ./master
    volumes:   
      - master-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=test
      - PG_REP_USER=replicator
    ports:
      - "15432:5432"
    networks:
      - test 
      
  replica-db:
    build: 
      context: ./slave
    volumes:   
      - slave-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=test
      - PG_REP_USER=replicator
    ports:
      - "15433:5432"
    depends_on: 
      - master-db
    networks:
      - test
      
networks:
  test:

volumes:
  master-data:
  slave-data: